language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0
git:
  depth: 10

before_install:
  - gem install bundler
  # we need a more recent cmake than travis/linux provides (at least 2.8.9):
  - echo 'yes' | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script: bundle update
