# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - git submodule init
  - git submodule update
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake